### PR TITLE
Bump to 24.3

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Invoking [CFEP-3](https://github.com/conda-forge/cfep/blob/main/cfep-03.md) to provide a manual build of `osx-arm64`.

This is the `.ci_support/osx_arm64_.yml` file I used (not available in this repo):

```yaml
MACOSX_DEPLOYMENT_TARGET:
- '11.0'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
macos_machine:
- arm64-apple-darwin20.0.0
target_platform:
- osx-arm64
```

Then I ran this command off current `main` (with this PR freshly merged):

```
MINIFORGE_HOME=~/opt/miniforge OSX_SDK_DIR=~/opt python build-locally.py osx_arm64_ 2>&1 | tee log.txt 
```

- This is the log file: [log.txt.zip](https://github.com/conda-forge/conda-standalone-feedstock/files/15282628/log.txt.zip)
- This is the package: https://anaconda.org/jaimergp/conda-standalone/files?channel=conda-standalone-24.3.0-0


cc @conda-forge/conda-standalone

**Comment by isuruf** [comment]
Looks good to me.

**Comment by jaimergp** [comment]
[Copied](https://anaconda.org/conda-forge/conda-standalone/files?version=24.3.0)!

```
$ anaconda copy --from-label conda-standalone-24.3.0-0 --to-label main --to-owner conda-forge jaimergp/conda-standalone/24.3.0

Using Anaconda API: https://api.anaconda.org
Copied file: osx-arm64/conda-standalone-24.3.0-hce30654_0.conda
Copied 1 files! 
```

**Pull request merged**
