### PR TITLE
Update to 4.8.5

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@nehaljwani, @jakirkham, @msarahan, @forrestwaters, this is ready for review

**Comment by nehaljwani** [comment]
Why is the `yum_requirements.txt` file needed?

**Comment by isuruf** [comment]
Because of the error at https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/211425/logs/18. I'm not sure why it is needed, but it seems to work.

**Comment by nehaljwani** [comment]
Got rid of it in: https://github.com/conda-forge/conda-standalone-feedstock/pull/9/commits/a856aec502d7afafa95c9c72c28d7130e62b11d8

**Comment by isuruf** [comment]
Thanks @nehaljwani

**Pull request merged**
