### PR TITLE
Bump to conda-standalone 24.1.2

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Looks good to me. Feel free to upload it to conda-forge/label/main.

**Comment by jakirkham** [comment]
> Invoking [CFEP-3](https://github.com/conda-forge/cfep/blob/main/cfep-03.md) to provide a manual build of `osx-arm64`.

@jaimergp am curious why we are not able to build this on CI? Is there more context somewhere?

**Comment by jaimergp** [comment]
PyInstaller doesn't support cross-compilation in a good way. I tried some hacks in https://github.com/conda-forge/conda-standalone-feedstock/pull/54 but it was too fragile (had to hard pin pyinstaller, and assumed both envs would solve in the same way). We'll have native CI at some point this year I assume, so in practice we only need to do this for a few more releases.

**Comment by jaimergp** [comment]
Upload complete: https://anaconda.org/conda-forge/conda-standalone/24.1.2/download/osx-arm64/conda-standalone-24.1.2-hce30654_0.conda

**Pull request merged**
