### PR TITLE
Bump conda version to 4.11.0 and python to 3.9.9

### PR DESCRIPTION
**Pull request by ericpre**
As mentioned in https://github.com/conda-forge/conda-standalone-feedstock/pull/24#discussion_r779419390.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [n/a] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [n/a] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ericpre** [comment]
@conda-forge-admin, please rerender

**Comment by ericpre** [comment]
@jaimergp, @conda-forge/conda-standalone, this is ready for review.

**Comment by jaimergp** [comment]
Can we enable Azure artifacts here? I had issues building conda-standalone locally with Python 3.9 before. It built correctly but then it failed to run on Windows due to SSL stuff. GHA CI didn't reproduce the issue because the ssl libraries were in PATH. Just want to make sure we can try locally first.

**Comment by ericpre** [comment]
@conda-forge-admin, please rerender

**Comment by ericpre** [comment]
Link to the artifcats: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=442794&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by jaimergp** [comment]
@jakirkham Any reason not to upgrade Python here?

**Comment by ericpre** [comment]
Ping @jaimergp and @jakirkham! :)

**Comment by jaimergp** [comment]
Well, let's give it a try. The only thing I can think of right now that could cause trouble is the [default spawn method](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) in multiprocessing for macos starting with 3.8+, but I don't think conda uses multiprocessing anywhere (nothing came up in the grep search).

**Comment by jaimergp** [comment]
I'll re-run the CI and then merge.

**Comment by ericpre** [comment]
> Well, let's give it a try. The only thing I can think of right now that could cause trouble is the [default spawn method](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) in multiprocessing for macos starting with 3.8+, but I don't think conda uses multiprocessing anywhere (nothing came up in the grep search).

Considering that `conda` is supported on python 3.9, I would not expect any particular issue here! Even if it happens not to be correct, in worse case scenario, the package can still be marked as broken.

The `conda-standalone` feedstock from AnacondaRecipes is using python 3.9: https://github.com/AnacondaRecipes/conda-standalone-feedstock/blob/master/recipe/meta.yaml

**Pull request merged**
