### PR TITLE
cleanup leftover symlink

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Comes from https://github.com/conda-forge/conda-standalone-feedstock/pull/69#issuecomment-1893873734

### CODE REVIEW

**Review by isuruf — COMMENTED** [review]
Let's add an empty `host` section instead?

**Comment by jaimergp** [comment]
That's redefining SP_DIR now too :cry:

**Comment by isuruf** [comment]
Ok. Let's go back to cleanup. Sorry.

**Comment by jaimergp** [comment]
Let's see if this is enough, if not I'll rollback.

**Comment by jaimergp** [comment]
@isuruf - this is ready now.

**Review by isuruf — APPROVED** [review]

**Review by isuruf — APPROVED** [review]

**Comment by jaimergp** [comment]
Invoking [CFEP-3](https://github.com/conda-forge/cfep/blob/main/cfep-03.md) to provide a manual build of `osx-arm64`, as discussed in #54 and then #69.

This is the `.ci_support/osx_arm64_.yml` file I used (not available in this repo):

```yaml
MACOSX_DEPLOYMENT_TARGET:
- '11.0'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
macos_machine:
- arm64-apple-darwin20.0.0
target_platform:
- osx-arm64
```

Then I ran this command off current `main` (with this PR freshly merged):

```
MINIFORGE_HOME=~/opt/miniforge OSX_SDK_DIR=~/opt python build-locally.py osx_arm64_ 2>&1 | tee log.txt 
```

Which produced the following output: [log.txt.zip](https://github.com/conda-forge/conda-standalone-feedstock/files/13953384/log.txt.zip)


The resulting artifact is available at https://anaconda.org/jaimergp/conda-standalone/files?channel=conda-standalone-23.11.0-1.

**Comment by isuruf** [comment]
Looks good to me.

**Comment by jaimergp** [comment]
```
$ anaconda copy --from-label conda-standalone-23.11.0-1 --to-label main --to-owner conda-forge jaimergp/conda-standalone/23.11.0             

Using Anaconda API: https://api.anaconda.org
Copied file: osx-arm64/conda-standalone-23.11.0-hce30654_1.conda
Copied 1 files! 
```

[And done](https://anaconda.org/conda-forge/conda-standalone/files?version=23.11.0)!

**Pull request merged**
